development: 
  :host: localhost
  :port: 6379
  :password:
  :database: 0
test: 
  :host: localhost
  :port: 6379
  :password: 
  :database: 0
production:
  :host: localhost
  :port: 6379
  :password:
  :database: 0